classDiagram
    class Developer {
        +int id
        +string first_name
        +string last_name
        +string title
        +string bio
        +string email
        +string phone
        +string location
        +string profile_picture
    }

    class Skill {
        +int id
        +string name
        +string level
        +string category
        +string icon
    }

    class Project {
        +int id
        +string title
        +string description
        +string image
        +string github_link
        +string demo_link
        +string technologies
        +date start_date
        +date end_date

    }

    %% Relationships
    Developer "1" --> "many" Project : has
    Developer "1" --> "many" Skill : has
    Project "many" --> "many" Skill : uses
